name: "Build & Deploy: Desktop"

env:
  GODOT_VERSION: 4.4.1

on:
  workflow_dispatch:
  push:
    branches:
      - ci

jobs:
  deploy-windows:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -v -p ~/.local/share/godot/export_templates
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          echo $PROJECT_PATH  # DEBUG
          echo "$EXPORT_DIR/windows/${GITHUB_REPOSITORY##*/}.exe"  # DEBUG
          stat "$EXPORT_DIR/windows"  # DEBUG
          ls  # DEBUG
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/${GITHUB_REPOSITORY##*/}.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows

