name: "Build & Deploy: Desktop"

env:
  GODOT_VERSION: 4.4.1

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-windows-x86_64:
    name: Windows (x86-64)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -v -p ~/.local/share/godot/export_templates
      - name: Build
        run: |
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "windows-x86_64" "$EXPORT_DIR/windows/${GITHUB_REPOSITORY##*/}-x86_64.exe"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: build/windows
  deploy-windows-arm64:
    name: Windows (arm64)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -v -p ~/.local/share/godot/export_templates
      - name: Build
        run: |
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "windows-arm64" "$EXPORT_DIR/windows/${GITHUB_REPOSITORY##*/}-arm64.exe"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64
          path: build/windows
  deploy-macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Godot
        run: brew install --cask godot
      - name: Install Godot MacOS export templates
        run: |
          curl -L -o templates.tpz "https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          mkdir -p ~/Library/Application\ Support/Godot/export_templates/${GODOT_VERSION}.stable
          unzip -q templates.tpz -d ~/Library/Application\ Support/Godot/export_templates/${GODOT_VERSION}.stable
          mv ~/Library/Application\ Support/Godot/export_templates/${GODOT_VERSION}.stable/templates/* ~/Library/Application\ Support/Godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "macos" "$EXPORT_DIR/macos/${GITHUB_REPOSITORY##*/}.dmg"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/macos
  deploy-linux-x86_64:
    name: Linux (x86-64)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -v -p ~/.local/share/godot/export_templates
      - name: Build
        run: |
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "linux-x86_64" "$EXPORT_DIR/linux/${GITHUB_REPOSITORY##*/}.dmg"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: build/linux
  deploy-linux-arm64:
    name: Linux (arm64)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -v -p ~/.local/share/godot/export_templates
      - name: Build
        run: |
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "linux-arm64" "$EXPORT_DIR/linux/${GITHUB_REPOSITORY##*/}.dmg"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: build/linux

